# Generated by Django 3.2.6 on 2021-09-10 23:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import songs.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('audio_file', models.FileField(upload_to='')),
                ('genre', models.CharField(max_length=255)),
                ('year', models.IntegerField(default=2021, validators=[django.core.validators.MinValueValidator(1984), songs.models.max_value_current_year])),
                ('duration', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('cover_image', models.FileField(upload_to='')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_artist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('audio_file', models.FileField(upload_to='')),
                ('genre', models.CharField(max_length=255)),
                ('year', models.IntegerField(default=2021, validators=[django.core.validators.MinValueValidator(1984), songs.models.max_value_current_year])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('duration', models.DecimalField(blank=True, decimal_places=2, max_digits=4)),
                ('cover_image', models.FileField(upload_to='')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_artist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
