# Generated by Django 3.2.6 on 2021-09-12 20:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_song_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
